server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mv_db?serverTimezone=GMT&characterEncoding=utf-8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: mv-db
logging:
  file:
    name: view.log

---

spring:
  profiles: dev

---

spring:
  profiles: proc
server:
  tomcat:
    max-connections: 1000
    max-threads: 200
    max-http-post-size: 2MB
